_: [
  (import ./repos/unstable.nix _)
  (import ./repos/nur.nix _)
  (import ./repos/agenix.nix _)
  (import ./repos/comin.nix _)
  (import ./repos/keyring.nix _)
  (import ./repos/agents.nix _)
  (import ./repos/vscode.nix _)
  (import ./repos/local.nix _)
  (import ./backports/rtk.nix _)
  (import ./backports/beads.nix _)
  (import ./backports/herdr.nix _)
  (import ./backports/skills.nix _)
  (import ./backports/mcporter.nix _)
  (import ./backports/mcporter.nix _)
  (import ./backports/openlogi.nix _)
  (import ./backports/codegraph.nix _)
  (import ./packages/android.nix _)
  (import ./tweaks/onlyoffice.nix _)
  (import ./tweaks/shortcut.nix _)
  (import ./tweaks/wayland.nix _)
  (import ./tweaks/konsole.nix _)
  (import ./bugfix/mcporter.nix _)
]
