{ tools, ... }:
{
  imports =
    (map tools.relative [
      "home/tsln/_common/base"
      "home/tsln/_common/cli"
      "home/tsln/_common/cli/editors"
      "home/tsln/_common/dev/agents/codex.nix"
      "home/tsln/_common/dev/languages/bun.nix"
      "home/tsln/_common/dev/languages/cxx.nix"
      "home/tsln/_common/dev/languages/git.nix"
      "home/tsln/_common/dev/languages/go.nix"
      "home/tsln/_common/dev/languages/nix.nix"
      "home/tsln/_common/dev/languages/nodejs.nix"
      "home/tsln/_common/dev/languages/rust.nix"
      "home/tsln/_common/dev/languages/dotfiles"
      "home/tsln/_common/dev/libraries/openssl.nix"
      "home/tsln/_common/dev/managers/dotfiles/kubectl.nix"
      "home/tsln/_common/dev/managers/fluxcd.nix"
      "home/tsln/_common/dev/managers/kubectl.nix"
      "home/tsln/_common/dev/utilities"
      "home/tsln/_common/gui/apps/bitwarden.nix"
      "home/tsln/_common/gui/apps/chromium.nix"
      "home/tsln/_common/gui/apps/datagrip.nix"
      "home/tsln/_common/gui/apps/filelight.nix"
      "home/tsln/_common/gui/apps/firefox.nix"
      "home/tsln/_common/gui/apps/hoppscotch.nix"
      "home/tsln/_common/gui/apps/insomnia.nix"
      "home/tsln/_common/gui/apps/konsole.nix"
      "home/tsln/_common/gui/apps/lark.nix"
      "home/tsln/_common/gui/apps/libreoffice.nix"
      "home/tsln/_common/gui/apps/netease.nix"
      "home/tsln/_common/gui/apps/qq.nix"
      "home/tsln/_common/gui/apps/vlc.nix"
      "home/tsln/_common/gui/apps/vscode.nix"
      "home/tsln/_common/gui/apps/wechat.nix"
      "home/tsln/_common/gui/desktop/plasma"
      "home/tsln/_common/i18n"
      "home/tsln/_common/themes"
    ])
    ++ (tools.scan ./.);
}
